### ISSUE TITLE
.xyz Error in config.in

### ISSUE THREAD

**Issue by sevkel** [blaschma/phonon_transport#3]
Code throws exception for invalid config file due to .xyz format of the geometry. Use .coord instead?

**Comment by blaschma** [comment]
Commit https://github.com/blaschma/phonon_transport/commit/a950bc9c1498599c5b013268e00a14aa1115915b solves problem in phonon_transport. Works only with [tmoutproc](https://github.com/blaschma/tmoutproc) commits >=10c009fd74bd38f83d7138614849cb4fc8ae9082
